Add a priority to flairs that can override the group priority
StratusNetwork/OCN pull request #47
Opened 2018-01-20 01:45 UTC by cswhite2000

2018-01-20 21:21 UTC, Electroid requested changes

2018-01-20 21:21 UTC, Electroid commented on app/models/user/groups.rb
> +                            priority: flair.priority ||= group.priority,
Should this be `flair.priority || group.priority`? `||=` is an assignment.

2018-01-20 21:21 UTC, Electroid commented on app/models/group.rb
> +    Flair = Struct.new(:symbol, :color, :priority)
While you're changing this, you might want to allow multiple colors to be defined. We wanted to try out bold flairs, but this was not possible given the one color code format.

2018-01-21 04:47 UTC, cswhite2000 commented on app/models/group.rb
> +    Flair = Struct.new(:symbol, :color, :priority)
Well you can add the color codes into the symbol string manually. All the color code does is translate the color into the minecraft formatting code and place that in front of the symbol string.

2018-01-25 03:59 UTC, Electroid approved these changes

2018-02-03 04:12 UTC, merged