Add emojis help post link
StratusNetwork/OCN pull request #63
Opened 2018-02-11 10:50 UTC by Matic0B

2018-02-16 17:38 UTC, Electroid requested changes

2018-02-16 17:38 UTC, Electroid commented on app/views/forem/posts/_form.haml
> +                        %a{:href => "https://stratus.network/forums/posts/5a7f78de7b10af00010002f9", :target => "_blank"}
Let’s make this a specific route. Like stratus.network/emoji

2018-02-27 20:17 UTC, Electroid commented
@Matic0B Resolve the conflicts so this can be merged.

2018-03-15 00:30 UTC, cswhite2000 approved these changes

2018-03-15 00:36 UTC, merged